name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          dub: dub

        - os: macos-latest
          dub: dub

        - os: windows-latest
          dub: dub.exe

    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1.0.3

      - name: Build
        run: ${{matrix.dub}} build --config=ci
